### ISSUE TITLE
io.js 2.0 support.

### ISSUE THREAD

**Issue by ChALkeR** [TooTallNate/node-weak#45] opened 2015-05-04 22:20 UTC
In `package.json`, `nan` module should be updated to `~1.8.0`. Or `^1.8.0` or `^1.6.4`, if you don't want to update `package.json` with every required `nan` version bump.

**Comment by seethroughtrees** [comment] 2015-05-09 18:29
Hi, it looks like this is fixed in the repo.  But maybe not pushed to npm?

**Comment by seethroughtrees** [comment] 2015-05-09 18:35
So, I have confirmed that installing the package from this repo instead of npm does fix the iojs support.  Which in turn fixes dnode, and all that depend on it.  

If there's any chance you could bump this in npm, that would be much appreciated.  Thanks.

**Comment by TooTallNate** [comment] 2015-08-17 21:52
Try v1.0.0 of node-weak please.

**Closed by TooTallNate** 2015-08-17 21:52 UTC
